#!/usr/bin/env python3
"""Generate C++ forward declarations for the top-level functions of a .pde.

Java doesn't care what order functions are defined in; C++ does. Processing's
own preprocessor solves this by emitting prototypes before handing the sketch
to the compiler, and this does the same so .pde files compile as C++ untouched.

Matches single-line signatures at column 0 (`void drawGradient(float x) {`).
Qualified names (`void Ball::move()`) are member definitions, not top-level
functions, and are skipped. A signature split across lines is not matched --
put it on one line, which every Processing example already does.
"""
import re
import sys

SIG = re.compile(r"^(void|int|float|double|bool|long|char)\s+([A-Za-z_]\w*)\s*\(([^)]*)\)\s*\{?\s*$")

src, dst = sys.argv[1], sys.argv[2]
protos = []
for line in open(src):
    m = SIG.match(line)
    if m:
        protos.append(f"{m.group(1)} {m.group(2)}({m.group(3)});")

with open(dst, "w") as f:
    f.write(f"// generated by tools/pde_prototypes.py from {src} -- do not edit\n")
    f.write("#pragma once\n")
    f.write("\n".join(protos) + "\n")
